'''
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
'''


def is_even(number):
    return number % 2 == 0


def fibs(n, a=1, b=2):
    while b < n:
        a, b = b, a + b
        yield b

if '__name__' == '__main__':
    print sum([x for x in fibs(4000000) if is_even(x)])
